Update Linux Mint App Installer

diff --git a/Linux Mint App Installer b/Linux Mint App Installer
--- a/Linux Mint App Installer
+++ b/Linux Mint App Installer
@@ -1,131 +1,186 @@
-clear
+#!/bin/bash
 
-echo -e "\e[1;34m Test for Linux Mint and nala. Updated July 9 2024. Make sure to click ok or yes at various points in install process. Don't Mix Danger, Handle with Care! \e[0m"
+# Still needs more testing!
+
+# List of .deb packages to install
+deb_packages=(
+  "ffmpegthumbnailer"
+  "fortune-mod"
+  "cowsay"
+  "nemo-preview"
+  "nemo-image-converter"
+  "folder-color-switcher"
+  "nemo-emblems"
+  "nemo-gtkhash"
+  "nemo-media-columns"
+  "ubuntu-restricted-extras"
+  "ffmpeg"
+  "mpv"
+  "mediainfo"
+  "vlc"
+  "youtube-dl"
+  "libdvdcss2"
+  "libssl-dev"
+  "libexpat1-dev"
+  "libgl1-mesa-dev"
+  "libgstreamer1.0-dev"
+  "libgstreamer-plugins-base1.0-dev"
+  "libgstreamer-plugins-bad1.0-dev"
+  "gstreamer1.0-plugins-bad"
+  "gstreamer1.0-qt5"
+  "nfs-common"
+  "cifs-utils"
+  "gamemode"
+  "gnome-tweaks"
+  "lutris"
+  "steam"
+  "cpu-x"
+  "python3"
+)
+
+# List of Flatpak applications to install
+flatpak_apps=(
+  "com.spotify.Client"
+  "org.libreoffice.LibreOffice"
+  "net.cozic.joplin_desktop"
+  "com.synology.SynologyDrive"
+  "com.brave.Browser"
+  "one.ablaze.floorp"
+  "org.kde.kdenlive"
+  "fr.handbrake.ghb"
+  "com.obsproject.Studio"
+  "io.missioncenter.MissionCenter"
+  "org.telegram.desktop"
+  "com.bitwarden.desktop"
+  "com.skype.Client"
+  "io.github.aandrew_me.ytdn"
+  "org.localsend.localsend_app"
+  "io.github.shiftey.Desktop"
+  "com.github.tchx84.Flatseal"
+  "org.gnome.Evolution"
+  "io.github.flattool.Warehouse"
+  "io.github.celluloid_player.Celluloid"
+)
+
+# Array to store the names of installed .deb packages and Flatpak applications
+installed_deb_packages=()
+installed_flatpak_apps=()
+
+
+echo -e "\e[1;34m Updated July 25 2024. Make sure to click ok or yes or enter at various points in install process. Don't Mix Danger, Handle with Care! \e[0m"
+sleep 2s
+
+echo -e "\e[1;34m Preparing system before installing the apps from the array lists script. \e[0m" 
 sleep 5s
-
-echo -e "\e[1;34m ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
-
-echo -e "\e[1;34m ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
-
-echo -e "\e[1;34m Preparing system before beging installation script. \e[0m" 
 
 sudo apt update
 sudo apt upgrade -y
 
-echo -e "\e[1;34m Installing nala. \e[0m" 
+echo -e "\e[1;34m Removing the old packaged version of Libre Office. We will install from flatpak later in the script. The flatpak version is more up to date. \e[0m"
 sleep 2s
 
-sudo apt install nala -y 
+sudo apt-get remove --purge "libreoffice*"
+sudo apt-get clean
+sudo apt-get autoremove
 
-echo -e "\e[1;34m Installing terminal tools. \e[0m" 
-sleep 2s
+echo -e "\e[1;34m Installing Nala. Becuase it is better than apt. \e[0m"
 
-sudo nala install ffmpegthumbnailer fortune-mod cowsay -y
+sudo apt install nala
 
-echo -e "\e[1;34m Installing Fastfetch. \e[0m" 
-sleep 2s
-
-sudo add-apt-repository ppa:zhangsongcui3371/fastfetch
-sudo apt update
-sudo apt install fastfetch
-
-echo -e "\e[1;34m Installing MakeMKV. \e[0m" 
+echo -e "\e[1;34m Installing MakeMKV from the heyarje repo. This one works better than the flathub one. \e[0m" 
 sleep 2s
 
 sudo add-apt-repository ppa:heyarje/makemkv-beta
 sudo apt update
 sudo nala install makemkv-bin makemkv-oss -y
 
-echo -e "\e[1;34m Installing codecs and media tools. \e[0m" 
+echo -e "\e[1;34m Installing Fastfetch from the zhangsongcui repo. Make sure to confirm actions. This step is needed until fastfest is available as a system or flatpak install. \e[0m" 
 sleep 2s
 
-sudo nala install ffmpeg mpv mediainfo vlc youtube-dl libdvdcss2 chromium-codecs-ffmpeg-extra libdvd-pkg libssl-dev libexpat1-dev libgl1-mesa-dev ubuntu-restricted-extras -y
+sudo add-apt-repository ppa:zhangsongcui3371/fastfetch
+sudo apt update
+sudo apt install fastfetch
+
+# Begin installing from array now.
+
+# Function to check if a .deb package is installed
+is_deb_installed() {
+  dpkg -l | grep -qw "$1"
+}
+
+# Function to check if a Flatpak application is installed
+is_flatpak_installed() {
+  flatpak list | grep -qw "$1"
+}
+
+# Update package list for .deb packages
+echo -e "\e[1;34m Updating package list...\e[0m"
+sudo nala update
+
+# Install each .deb package if not already installed
+for package in "${deb_packages[@]}"; do
+  if is_deb_installed "$package"; then
+    echo -e "\e[1;34m $package is already installed, skipping. \e[0m"
+  else
+    echo -e "\e[1;34m Installing $package...\e[0m"
+    sudo nala install -y "$package"
+    if [ $? -eq 0 ]; then
+      installed_deb_packages+=("$package")
+    else
+      echo -e "\e[1;34m Failed to install $package. "
+    fi
+  fi
+done
+
+# Install Flatpak if not already installed
+if ! command -v flatpak &> /dev/null; then
+  echo -e "\e[1;34m Flatpak is not installed, installing Flatpak... \e[0m"
+  sudo nala install -y flatpak
+fi
+
+# Install each Flatpak application if not already installed
+for app in "${flatpak_apps[@]}"; do
+  if is_flatpak_installed "$app"; then
+    echo -e "\e[1;34m $app is already installed, skipping. \e[0m"
+  else
+    echo -e "\e[1;34m Installing $app... \e[0m"
+    flatpak install -y flathub "$app"
+    if [ $? -eq 0 ]; then
+      installed_flatpak_apps+=("$app")
+    else
+      echo -e "\e[1;34m Failed to install $app. \e[0m"
+    fi
+  fi
+done
+
+
+# Configuring libdvd.
+
+echo -e "\e[1;34m Configuring libdvd-pkg. \e[0m" 
+sleep 2s
 
 sudo dpkg-reconfigure libdvd-pkg
 
-echo -e "\e[1;34m Installing gstreeamer tools. \e[0m"
+# Generate report
+if [ ${#installed_deb_packages[@]} -eq 0 ] && [ ${#installed_flatpak_apps[@]} -eq 0 ]; then
+  echo -e "\e[1;34m No new programs were installed. \e[0m"
+else
+  echo -e "\e[1;34m The following .deb packages were installed: \e[0m"
+  for package in "${installed_deb_packages[@]}"; do
+    echo "- $package"
+  done
+  echo -e "\e[1;34m The following Flatpak applications were installed: \e[0m"
+  for app in "${installed_flatpak_apps[@]}"; do
+    echo "- $app"
+  done
+fi
 
-sudo nala install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio -y
+echo -e "\e[1;34m +++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
 
-echo -e "\e[1;34m Installing network file sharing tools. \e[0m" 
-sleep 2s
-
-sudo nala install nfs-common cifs-utils -y
-
-echo -e "\e[1;34m Now entering the Flatpak zone. \e[0m" 
-
-echo -e "\e[1;34m Installing Libre Office Flatpak. More up to date the install with OS. \e[0m"
-
-flatpak install flathub org.libreoffice.LibreOffice  -y
-
-echo -e "\e[1;34m Installing Joplin Flatpak. \e[0m"
-
-flatpak install flathub net.cozic.joplin_desktop -y
-
-echo -e "\e[1;34m Installing Synology Drive Station. \e[0m"
-
-flatpak install flathub com.synology.SynologyDrive -y
-
-echo -e "\e[1;34m Installing Brave. \e[0m"
-
-flatpak install flathub com.brave.Browser -y
-
-echo -e "\e[1;34m Installing Floorp. \e[0m"
-
-flatpak install flathub one.ablaze.floorp -y
-
-echo -e "\e[1;34m Installing Kdenlive Flatpak. \e[0m"
-
-flatpak install flathub org.kde.kdenlive -y
-
-echo -e "\e[1;34m Installing Spotube Spotify client Flatpak. \e[0m"
-
-flatpak install flathub com.github.KRTirtho.Spotube -y
-
-echo -e "\e[1;34m Installing Handbrake Flatpak. \e[0m"
-
-flatpak install flathub fr.handbrake.ghb -y
-
-echo -e "\e[1;34m Installing OBS Studio Flatpak. \e[0m"
-
-flatpak install flathub com.obsproject.Studio -y
-
-echo -e "\e[1;34m Installing Mission Center Flatpak. \e[0m"
-
-flatpak install flathub io.missioncenter.MissionCenter -y
-
-echo -e "\e[1;34m Installing Telegram Flatpak. \e[0m"
-
-flatpak install flathub org.telegram.desktop -y
-
-echo -e "\e[1;34m Installing Bitwarden Flatpak. \e[0m"
-
-flatpak install flathub com.bitwarden.desktop -y
-
-echo -e "\e[1;34m Installing Skype Flatpak. \e[0m"
-
-flatpak install flathub com.skype.Client -y
-
-echo -e "\e[1;34m Installing Youtube Downloader Flatpak. \e[0m"
-
-flatpak install flathub io.github.aandrew_me.ytdn -y
-
-echo -e "\e[1;34m Installing LocalSend Flatpak. \e[0m"
-
-flatpak install flathub org.localsend.localsend_app -y
-
-echo -e "\e[1;34m ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
-
-echo -e "\e[1;34m ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
+echo -e "\e[1;34m +++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
 
 echo -e "\e[1;34m Finished scripted installations. Shop Smart, shop S-Mart. \e[0m"
 
-echo -e "\e[1;34m ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
+echo -e "\e[1;34m +++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
 
-echo -e "\e[1;34m ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
-
-sleep 10s
-
-clear
-
-exit
+echo -e "\e[1;34m +++++++++++++++++++++++++++++++++++++++++++++++ \e[0m"
